name: bid_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0
  get_storage: ^2.0.3
  connectivity_plus: ^3.0.2
  get: ^4.6.5
  flutter_spinkit: ^5.1.0
  getwidget: ^3.0.1
  syncfusion_flutter_core: ^20.4.43
  syncfusion_flutter_maps: ^20.4.43
  syncfusion_flutter_charts: ^20.4.43
  intl: ^0.17.0
  darq: ^1.2.1
  flutter_jailbreak_detection: ^1.10.0
  device_info_plus: ^8.0.0
  carousel_slider: ^4.2.1
  flutter_svg: ^1.1.6
  flutter_native_splash: ^2.2.16
  root_check: ^0.0.2+1
  dropdown_search: ^5.0.5


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_launcher.jpg"



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/certificates/
    - assets/world-map.json


  fonts:
    - family: Pilat Light
      fonts:
        - asset: assets/fonts/Pilat-Light.ttf
          weight: 300
    - family: Pilat Demi
      fonts:
        - asset: assets/fonts/Pilat-Demi.ttf
          weight: 700
    - family: Pilat Heavy
      fonts:
        - asset: assets/fonts/Pilat-Wide-Heavy.ttf
          weight: 900

