name: bid_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.1.0+3

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  get_storage: ^2.0.3
  connectivity_plus: ^4.0.0
  get: ^4.6.5
  flutter_spinkit: ^5.1.0
  getwidget: ^3.0.1
  syncfusion_flutter_core: ^21.2.4
  syncfusion_flutter_maps: ^21.2.4
  syncfusion_flutter_charts: ^21.2.4
  intl: ^0.18.1
  darq: ^1.2.1
  flutter_jailbreak_detection: ^1.10.0
  device_info_plus: ^9.0.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.5
  flutter_native_splash: ^2.2.16
  root_check: ^0.0.2+1
  dropdown_search: ^5.0.5
  google_maps_flutter: ^2.2.3
  scrollable_positioned_list: ^0.3.5


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/DPW_LOGO_B&W.jpg"



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/certificates/
    - assets/world-map.json


  fonts:
    - family: Pilat Light
      fonts:
        - asset: assets/fonts/Pilat-Light.ttf
          weight: 300
    - family: Pilat Demi
      fonts:
        - asset: assets/fonts/Pilat-Demi.ttf
          weight: 700
    - family: Pilat Heavy
      fonts:
        - asset: assets/fonts/Pilat-Wide-Heavy.ttf
          weight: 900

